name         'example42-stdmod'
version      '3.0.0'
author       'Alessandro Franceschi'
license      'Apache2'
project_page 'http://www.example42.com'
source  'https://github.com/example42/puppet-stdmod'
summary 'Puppet module for stdmod'
description 'This module installs and manages stdmod. Check README for details.'
dependency 'puppetlabs/stdlib', '>=2.0.0'
